name: system_space
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    platforms:
      linux:
        package: .
        pluginClass: SystemSpacePlugin
      macos:
        package: .
        pluginClass: SystemSpacePlugin
      windows:
        package: .
        pluginClass: SystemSpacePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
